### ISSUE TITLE
Is it just a little endian + copy converter for rust?

### ISSUE THREAD

**Issue by maoxs2** [nervosnetwork/molecule#10]
With only one line introduction, I dont know how this crate works for the serialization. I simply checked the https://github.com/yangby-cryptape/molecule/tree/master/bindings/rust folder, it shows me that you are just warpping the primitive rust types in your OOP favor.

So is it just for little endian convertion? Or having any other difference on the scope of bytes?

**Comment by driftluo** [comment]
https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0008-serialization/0008-serialization.md

The result of this serialization is only `bytes` or called `slices`.

The underlying data structure is byte ie u8

Regardless of the type, it will be converted to the format of `header | body`

Serialization itself does not have the distinction between big and little ends. When users set big-endian data, they must read it in big-endian mode, and vice versa.
