### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by WilfredTA** [nervosnetwork/molecule#14]
Can we please add documentation on molecule's API and convenience methods ASAP, as well as some simple code examples of how to work with it in the context of ckb scripts?

Another thing that would be useful is for showing how the args created on generator side to deploy a script are then used with molecule during script execution.

**Comment by doitian** [comment]
Extra context

> Hey Ian, you mentioned using molecule for arg parsing in scripts. Just wondering a couple things:
> 
> 1. Is there a guide for basic molecule usage? Or some simple scripts that use it as an example?
> 2. I'm using the Js-SDK; how should args be serialized on the generator side to parse them with molecule on script side? 
> 
> I think an example code with a simple script that takes multiple args and the code that deploys that script to CKB would be enough for me to answer those questions if there are no docs for it

**Comment by yangby-cryptape** [comment]
> Can we please add documentation on molecule's API and convenience methods ASAP, as well as some simple code examples of how to work with it in the context of ckb scripts?
> 
> Another thing that would be useful is for showing how the args created on generator side to deploy a script are then used with molecule during script execution.

If you have read the [`README.md`](https://github.com/nervosnetwork/molecule/blob/fc227a1d2868de1b8da8b38f1c94af998badbc7a/README.md), you should found this repository is only focus on define a serialization system.
So there are no CKB data structures in this repository.
They are defined in [CKB repository](https://github.com/nervosnetwork/ckb/blob/v0.26.1/util/types/schemas/blockchain.mol);

We already had [a document about serialization HERE](https://github.com/nervosnetwork/rfcs/blob/3e0d5f65f199450d9392e91f06779dad68317271/rfcs/0008-serialization/0008-serialization.md), and I will copy them to this repository.
For the moment, you can read them.
And there are [a lot of Rust and C examples for serialization](https://github.com/nervosnetwork/molecule/tree/master/examples/ci-tests).

> 2\. I'm using the Js-SDK; how should args be serialized on the generator side to parse them with molecule on script side?

At present, this repository is only provide Rust and C implementations for serialization.
No Javascript code in this repository.

If you have used JS-SDK for CKB, you should find [THIS](https://github.com/nervosnetwork/ckb-sdk-js/tree/9f0d1b6a9fc0db0121ca59870aa1cc4ef3acc55d/packages/ckb-sdk-utils/src/serialization).
I didn't read or write javascript code. I just found this after check that repository in 3 minutes, so I'm not sure if it is what you want.
If you have more questions about CKB-JS-SDK APIs, you should submit issues in that repository, their answers will better than mine.

#### Summary

1. Read  [this document](https://github.com/nervosnetwork/rfcs/blob/3e0d5f65f199450d9392e91f06779dad68317271/rfcs/0008-serialization/0008-serialization.md) to understand serialization.
2. Read [this schema](https://github.com/nervosnetwork/ckb/blob/v0.26.1/util/types/schemas/blockchain.mol) to know CKB data structures. 
3. Read [these code](https://github.com/nervosnetwork/ckb-sdk-js/tree/9f0d1b6a9fc0db0121ca59870aa1cc4ef3acc55d/packages/ckb-sdk-utils/src/serialization) to know how to use serialization via CKB-JS-SDK.

**Comment by WilfredTA** [comment]
I understand that molecule is to support rust and c **scripts**. What I am asking is:

If I am deploying a C script, and I use js-sdk or ruby sdk etc., how do I encode the args in the sdk generator code such that they are able to be read by molecule by the on-chain C code? This is since we have no C or rust SDK at this moment

**Comment by doitian** [comment]
Since there's no JavaScript and Ruby code generators, I recommend following ways to serialize args:

- Use a mature serialization framework which supports both C and the SDK language, such as protobuf, rlp.
- If the args only contains variable length strings, use a simple frame encoding such as length prefix frames.
- Use a general molecule schema like a variable length list of Bytes, and manually implement the builder in the target SDK language.

**Comment by doitian** [comment]
Duplicated of https://github.com/nervosnetwork/docs/issues/114
