### ISSUE TITLE
Rust generated code with "::molecule::..."

### ISSUE THREAD

**Issue by XuJiandong** [nervosnetwork/molecule#40]
See generated code below:
"-" is old code, "+" is the new one.
```
-    fn write<W: ::molecule::io::Write>(&self, writer: &mut W) -> ::molecule::io::Result<()> {
+    fn write<W: molecule::io::Write>(&self, writer: &mut W) -> molecule::io::Result<()> {

```
It's better to be without "::".

**Comment by yangby-cryptape** [comment]
Sorry, I didn't see this PR until today.

Yes, the `::` is useless.

At the beginning, here is `::std::io`. For the `no-std` feature, I replaced all `std::io` to `molecule::io`, so it became to this style.
