### ISSUE TITLE
why has code  Self::FIELD_COUNT == 0 is always false, because Self::FIELD_COUNT is const and always 3

### ISSUE THREAD

**Issue by sjatsh** [nervosnetwork/molecule#60]
<img width="890" alt="image" src="https://user-images.githubusercontent.com/16359798/207015926-c3a75180-5eee-45f6-afa3-984dbc25f676.png">

**Comment by zhangsoledad** [comment]
It looks like it should be `self.field_count()`， @yangby-cryptape

**Comment by yangby-cryptape** [comment]
This piece of code is correct, but it could be optimized off in the code generator.

The condition `slice_len == 4` is satisfied if and only if when the `table` is defined with no fields.

- If u define a empty table, such as:

  ```
  table EmptyTable {}
  ```

  If `slice_len == 4`, it could return a `Ok(_)`.

- But if a table has at least 1 field, it has to return an `Err(_)`.
